snap:
  stage: build
  script:
    - snapcraft clean
    - snapcraft
  artifacts:
    paths:
      - "*.snap"
    expire_in: 1 week

test-snap:
  stage: test
  variables:
    GIT_CLEAN_FLAGS: none
  script:
    - review-tools.snap-review *.snap
